import { Worker } from 'bullmq'
import { generateQuestion } from '../../../packages/LLM/router'
import { db, questions } from '../../../packages/db/src/index'
import { and, eq, inArray } from "drizzle-orm";
import { v4 as uuid } from 'uuid'
import { error } from 'node:console';
export interface Options {
    id: string,
    selectedOptionId: string
    text: string
}
export interface Question {
    explanation: string,
    topic: string,
    correctOptions: string[],
    options: Options[],
    selectedOptionId: string
    questionId: string,
    description: string
    code: string
    difficulty: string
    questionType: string,
    language: string,
    totalTime: number,

}

const questionGenerationWorker = new Worker(
    "questionQueue",
    async (job) => {
        let parsedQuestions
        try {
            console.log("Worker started executing its task");
            const { topic, difficulty, language, questionLength, questionType } = job.data;
            const input = { topic, difficulty, language, questionLength, questionType };
            console.log("questions has been created")
            try {
                const createQuestions = await generateQuestion(input);
                console.log("createQuestions :", createQuestions)
                if (createQuestions.endsWith("]")) {
                    typeof (createQuestions) == "string" ? parsedQuestions = JSON.parse(createQuestions) : parsedQuestions = createQuestions
                    console.log("parsed ques :", parsedQuestions);
                    console.log(typeof (parsedQuestions))
                    const finalQuestions = parsedQuestions.map((q: Question) => ({
                        ...q,
                        questionId: uuid()
                    }))
                    const saveToDB = await db.insert(questions).values(parsedQuestions);

                    console.log("saved to db:", saveToDB);
                }
                else{
                    throw error
                }
            } catch (err: any) {
                console.log("error while saving the questions generated by worker in db:", err.message);
                throw err
            }
        } catch (err: any) {
            console.error("QUESTION GENERATOR WORKER ERROR:", err);
            console.log("Error:", err.message);
            throw err
        }
    },
    {
        connection: {
            url: process.env.REDIS_URL
        }
    },
)

const questionStatusChangerWorker = new Worker(
    "statusQueue",
    async (job) => {
        try {
            const { quesId } = job.data;
            if (quesId.length === 0 || !quesId) {
                console.log("quesId length is 0 ")
                return

            }
            await db.update(questions).set({ status: "used" }).where(inArray(questions.questionId, quesId))
            console.log("updating the status of the questions used")
        } catch (err) {
            console.error("STATUS CHANGER WORKER ERROR:", err);
        }
    },
    {
        connection: {
            url: process.env.REDIS_URL
        }
    },
)















